name: CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Replace toc-versions
        uses: Numynum/ToCVersions@master

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.WORKFLOW_OAUTH }}
          CF_API_KEY: ${{ github.event_name == 'release' && secrets.CF_API_KEY || '' }}
          WOWI_API_TOKEN: ${{ github.event_name == 'release' && secrets.WOWI_API_TOKEN || '' }}

      - name: Upload package
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: addon-package
          path: .release/*.zip
